name: CI Angular

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-shared-ci:
    uses: meditrack-yca/meditrack-actions/.github/workflows/shared.yml@main
    with:
      node-version: '22.x'
      test-command: 'npm run test:ci'
      run-build: true
      build-command: 'npm run build'
      artifact-name: 'dist-front'
      artifact-path: 'dist/'
      target-env: 'staging'
    secrets: inherit